CLUSTAL O(1.2.3) multiple sequence alignment


P21127      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      ------------------------------------------------------------
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      ------------------------------------------------------------
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      MPSSSDTALGGGGGLSWAEKKLEERRKRRRFLSPQQPPLLLPLLQPQLLQPPPPPPPLLF
Q07002      ------------------------------------------------------------
P24941      ------------------------------------------------------------
O94921      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
                                                                        

P21127      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      --------------------------------MPNSERHGGKKDGSGGASGTLQPSSGGG
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      ------------------------------------------------------------
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      LAAPGTAAAAAAAAAASSSCFSPGPPLEVKRLARGKRRAGGRQKRRRG------PRAG--
Q07002      ------------------------------------------------------------
P24941      ------------------------------------------------------------
O94921      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
                                                                        

P21127      ---------------------------------------------------------MGD
Q9BWU1      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      SSNSRERHRLVSKHKRHKSKHSKDMGLVTPEAASLGTVIKPLVEYDDISSDSDTFSD--D
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      ---------------------------------------------------------MGD
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      --QEAEKRRVFSLPQP---------QQDGGGGASSGGGVTPLVEYEDVSSQSEQGLLLGG
Q07002      ------------------------------------------------------------
P24941      ------------------------------------------------------------
O94921      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
                                                                        

P21127      EKDSWKVKTLDE---------ILQEKKRRKEQEE-----------------------KAE
Q9BWU1      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      MAFKLD---------------RRENDERRGSDRS----------DRLHKHRHHQHRRSRD
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      EKDSWKVKTLDE---------ILQEKKRRKEQEE-----------------------KAE
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      ASAATAATAAGGTGGSGGSPASSSGTQRRGEGSERRPRRDRRSSSGRSKERHREHRRRDG
Q07002      ------------------------------------------------------------
P24941      ------------------------------------------------------------
O94921      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
                                                                        

P21127      IKRLKNSDDRDSKRDSLEEGELRDHRMEITIRNSPYRREDSMEDRGEEDDSLAIK---PP
Q9BWU1      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      LLKAKQTEKEKSQEVSSKSGSMKDR---IS--GSSK------RSNEETDDYGKAQVAKSS
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      IKRLKNSDDRDSKRDSLEEGELRDHCMEITIRNSPYRREDSMEDRGEEDDSLAIK---PP
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      QRGGSEA--SKSRSRHSHSGEERAE---VAKSGSSS------SSGGRR-KSASATSSSSS
Q07002      ------------------------------------------------------------
P24941      ------------------------------------------------------------
O94921      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
                                                                        

P21127      QQMSRKEKAHHRKDEKRKEKRRHRSHSAEGGKHARVKEKEREHERRKRHREEQDKARREW
Q9BWU1      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      SKESRSSKLHKEKTRKEREL--KSGHK-DRSKSHRKRETPKSYKTVDSPKRRSRSPHRKW
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      QQMSRKEKVHHRKDEKRKEKWKHA------------RVKEREHERRKRHREEQDKARREW
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      SRKDRDSKAHRS-------------------RTKSSKEPPSAYKEPPKAYREDK------
Q07002      ------------------------------------------------------------
P24941      ------------------------------------------------------------
O94921      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
                                                                        

P21127      ERQKRREMAREHS-RRERDRLEQLERKR--------------ERERKMREQQKEQREQKE
Q9BWU1      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      SDSSKQDDSPSGASYGQDYDLSPSRSHTSSNYDSYKKSPGSTSRRQSVSPPYKEPSAYQS
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      ERQKRREMAREHS-RRERDRLEQLERKR--------------ERERKMREQQKEQREQKE
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      ---------TEPKAYRRRRSLSPLGGRDD--------SPVSHRASQSLR-SRKSP---SP
Q07002      ------------------------------------------------------------
P24941      ------------------------------------------------------------
O94921      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
                                                                        

P21127      RERRAEERRKEREARREVSAHHRTMREDY------S-------DKVKASHWSRSPPR---
Q9BWU1      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      STR-S-PSPYSRR-QRSVSPYSRRRSSSYERSGSYSGR---SPSPYGR---RRSSSPFLS
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      RERRAEERRKEREARREVSAHHRTMREDY------S-------DKVKASHWSRSPPR---
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      AGG-G-SSPYSRRLPRSPSPYSRRRSPSYSRHSSYERGGDVSPSPYSSSSWRRSRSPYS-
Q07002      ------------------------------------------------------------
P24941      ------------------------------------------------------------
O94921      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
                                                                        

P21127      --------PPRERFELGDGRKPGEARPAPAQKPAQLKE-----EKMEER--DLLSDLQDI
Q9BWU1      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      KRSLSRSPLPSRKSMKSRSRSPAYSRHSSSHSKKKRSSSRSRHSSISPVRLPLNSSLGAE
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      --------PPRERFELGDGRKPGEARPAPAQKPAQLKE-----EKMEER--DLLSDLQDI
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      --------PVLRRSGKSRSRSPYSSRHSRSRSRHRLSRSRSRHSSISPSTLTLKSSLAAE
Q07002      ----------------------------------------------------------MI
P24941      ------------------------------------------------------------
O94921      -----------------------------------------MCDLIEP-------QPAEK
Q00537      ------------------------------------------------------------
                                                                        

P21127      SDSERKTSSAESSSAESGSGSEEEE------------------------EEEEE-EEEEG
Q9BWU1      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      LSRKKKERAAA-AAAAKMDGKESKGSPVFLPRKENSSVEAKDSGLESKKLPRSVKLEKSA
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      MDRMKKIKRQL-SMTLRGGRGIDKT--------------------NGA--PEQIGLDESG
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      SDSERKTSSAESSSAESGSGSEEEE------------------------EEEEE-EEEEG
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      LNKNKKARA---AEAARAAEAAKAA--------------------EATKAAEAA--AKAA
Q07002      MNKMKNFKRRF-SLSVPRTETIEES--------------------LAE-FTEQFNQLHNR
P24941      ------------------------------------------------------------
O94921      IGKMKKLRRTL-SESFSRIAL-----------------------------------KKDD
Q00537      ---MKKFKRRL-SLTLRGSQTIDES--------------------LSE-LAEQMTIEENS
                                                                        

P21127      STSEESEEEEE---------------EEEEE----------------------EEETGSN
Q9BWU1      ------------------------------------------------------------
Q96Q40      -MGQELCAKTV-----------------------------QPGCSCY------HCSEGGE
Q00526      ------------------------------------------------------------
Q9NYV4      PDTELVNVTHLNTEVKNSSDTGKVKLDENSEKHLVKDLKAQGTRDSKPIALKEEIVTPKE
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      GGG-------GS----------------------------DPGEA-P------TRAAPGE
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      STSEESEEEEE---------------EEEEE----------------------EEETGSN
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      KASNTSTPTKGNTETSASASQ--------T--NHVKDVKKIKIEHAP------SPSSGGT
Q07002      RNENLQLGPLGRDPPQE-------------------------------------------
P24941      ------------------------------------------------------------
O94921      TTFDEICVTKM-----------------------------S----TR------NCQGMDS
Q00537      SKDNEPIVKNGRPPTSHSMHS--------FLHQYTGSFKKPPLRR-P------HSVIGGS
                                                                        

P21127      S-----------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q96Q40      A-----H--SC----------R--------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      TETSEKETPPPLPTIASPPPPLPTTTPPPQTPPLPPLPPIPALPQQPPLPPSQPAFSQVP
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      LRS--AR--GP----------L--------------------------------------
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      S-----------------------------------------------------------
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      LKNDKAKTKPP----------LQVTK-------V-----------ENNLIVDKATKKAVI
Q07002      ------------------------------------------------------------
P24941      ------------------------------------------------------------
O94921      V-----I--KP----------L--------------------------------------
Q00537      LGSFMAM--PR----------N--------------------------------------
                                                                        

P21127      -------EEASEQSAEEVSEEEM-------SED-EERENEN--HL-------LVVPES--
Q9BWU1      ------------------------------------------------------------
Q96Q40      ----RSQPETTE---AAFKLT---------DLK--EA---S--CS-MTSFHPRGLQAA--
Q00526      ------------------------------------------------------------
Q9NYV4      ASSTSTLPPSTHSKTSAVSSQANSQPPVQVSVKTQVSVTAAIPHLKTSTLPPLPLPPLLP
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      ----SSAPEIVH---EDLKMG---------SDG--ES--DQ--AS-ATSSDEVQSPVR--
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      -------EEASEQSAEEVSEEEM-------SED-EERENEN--HL-------LVVPES--
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      VGKESKSAATKE---ESVSLKEK-TKPLTPSIG--AKEKEQHVALVTSTLPPLPLPPMLP
Q07002      -----------C---STFSPT---------DSG-------E--EP-G-----QLSPGV--
P24941      ------------------------------------------------------------
O94921      ----DTIPEDKK---V--------------RVQ--RT---------QSTFDPFEKPAN--
Q00537      ----GSRLDIVH---ENLKMG---------SDG--ES--DQ--AS-GTSSDEVQSPTG--
                                                                        

P21127      -----RFDRDSGESEEAEEEVG-------EGTPQSSALTEGDYVP-DSPALS--------
Q9BWU1      ----------------------------------------------------------MD
Q96Q40      -----RAQKFKSKRPRSN-----------------SDCFQEEDLR---------------
Q00526      ------------------------------------------------------------
Q9NYV4      GDDDMDSPKETLPSKPVKKEKEQRTRHLLTDLPLPPELPGGDLSPPDSPEPKAITPPQQP
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      -----VRMRNHPPRKISTEDINK-RLSLPADIRLPEGYLEKLTLNSPIFDKP--------
P49336      ----------------------------------------------------------MD
Q15131      -------------------------------------MAEPDLEC-EQIRLK--------
Q00535      ------------------------------------------------------------
Q9UQ88      -----RFDRDSGESEEAEEEVG-------EGTPQSSALTEGDYVP-DSPALL--------
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      EDKEADSLRGNISVKAVKKEVEKKLRCLLADLPLPPELPGGDDLSKSPEEKK--TATQLH
Q07002      -----QFQRRQNQRRFSMEDVSK-RLSLPMDIRLPQEFLQKLQMESPDLPKP--------
P24941      ------------------------------------------------------------
O94921      -----QVKRV----HSEN-----------------NACINFKTSSTGKESPK--------
Q00537      -----VCLRNRIHRRISMEDLNK-RLSLPADIRIPDGYLEKLQINSPPFDQP--------
                                                                        

P21127      -------PIELKQE-LPKYLPALQGCRSVEEFQCLNRIEEGTYGVVYRAKDKK-TDE-IV
Q9BWU1      YDFKAKLAAERER------------VEDLFEYE-GCKVGRGTYGHVYKARRKDGKDEKEY
Q96Q40      -----------QG--FQWRK--SLPFGAASSYLNLEKLGEGSYATVYKGISRI-NGQ-LV
Q00526      ----------------------------MDMFQKVEKIGEGTYGVVYKAKNRE-TGQ-LV
Q9NYV4      YKKRPKICCPRYG--ERRQTESDWGKRCVDKFDIIGIIGEGTYGQVYKAKDKD-TGE-LV
P50750      -------MA------KQYDSVECPFCDEVSKYEKLAKIGQGTFGEVFKARHRK-TGQ-KV
P50613      ------------------MA--LDVKSRAKRYEKLDFLGEGQFATVYKARDKN-TNQ-IV
Q00534      -------------------MEKDGLCRADQQYECVAEIGEGAYGKVFKARDLKNGGR-FV
Q00536      -------LSRRLR--RVSLS--EIGFGKLETYIKLDKLGEGTYATVYKGKSKL-TDN-LV
P49336      YDFKVKLSSERER------------VEDLFEYE-GCKVGRGTYGHVYKAKRKDGKDDKDY
Q15131      -------CIRKEGFFTVPPEHRLGRCRSVKEFEKLNRIGEGTYGIVYRARDTQ-TDE-IV
Q00535      ----------------------------MQKYEKLEKIGEGTYGTVFKAKNRE-THE-IV
Q9UQ88      -------PIELKQE-LPKYLPALQGCRSVEEFQCLNRIEEGTYGVVYRAKDKK-TDE-IV
P11802      --------------------------MATSRYEPVAEIGVGAYGTVYKARDPH-SGH-FV
P06493      ----------------------------MEDYTKIEKIGEGTYGVVYKGRHKT-TGQ-VV
Q8IZL9      ----------------------------MDQYCILGRIGEGAHGIVFKAKHVE-TGE-IV
Q14004      SKRRPKICGPRYG--ETKEKDIDWGKRCVDKFDIIGIIGEGTYGQVYKARDKD-TGE-MV
Q07002      -------LSRMSR--RASLS--DIGFGKLETYVKLDKLGEGTYATVFKGRSKL-TEN-LV
P24941      ----------------------------MENFQKVEKIGEGTYGVVYKARNKL-TGE-VV
O94921      -------VRRHSS--PSSPT--SPKFGKADSYEKLEKLGEGSYATVYKGKSKV-NGK-LV
Q00537      -------MSRRSR--RASLS--EIGFGKMETYIKLEKLGEGTYATVYKGRSKL-TEN-LV
                                           :     :  * .. *::.           

P21127      ALKRLKMEKE---KEGFPITSLREINTILKA---QHPN-IVTVREIVVGS--------NM
Q9BWU1      ALKQI----E---GTGISMSACREIALLREL---KHPN-VIALQKVFLSH--------SD
Q96Q40      ALKVISMNA----EEGVPFTAIREASLLKGL---KHAN-IVLLHDIIH----------TK
Q00526      ALKKIRLDLE---MEGVPSTAIREISLLKEL---KHPN-IVRLLDVVH----------NE
Q9NYV4      ALKKVRLDNE---KEGFPITAIREIKILRQL---IHRS-VVNMKEIVTDKQDALDFKKDK
P50750      ALKKVLMENE---KEGFPITALREIKILQLL---KHEN-VVNLIEICRTKASP--YNRCK
P50613      AIKKIKLGHRSEAKDGINRTALREIKLLQEL---SHPN-IIGLLDAFG----------HK
Q00534      ALKRVRVQTG---EEGMPLSTIREVAVLRHLETFEHPN-VVRLFDVCTVS-----RTDRE
Q00536      ALKEIRLEH----EEGAPCTAIREVSLLKDL---KHAN-IVTLHDIIH----------TE
P49336      ALKQI----E---GTGISMSACREIALLREL---KHPN-VISLQKVFLSH--------AD
Q15131      ALKKVRMDKE---KDGIPISSLREITLLLRL---RHPN-IVELKEVVVGN--------HL
Q00535      ALKRVRLDDD---DEGVPSSALREICLLKEL---KHKN-IVRLHDVLH----------SD
Q9UQ88      ALKRLKMEKE---KEGFPITSLREINTILKA---QHPN-IVTVREIVVGS--------NM
P11802      ALKSVRVPNGGGGGGGLPISTVREVALLRRLEAFEHPN-VVRLMDVCATS-----RTDRE
P06493      AMKKIRLESE---EEGVPSTAIREISLLKEL---RHPN-IVSLQDVLM----------QD
Q8IZL9      ALKKVALRRL---EDGFPNQALREIKALQEM---EDNQYVVQLKAVFP----------HG
Q14004      ALKKVRLDNE---KEGFPITAIREIKILRQL---THQS-IINMKEIVTDKEDALDFKKDK
Q07002      ALKEIRLEH----EEGAPCTAIREVSLLKNL---KHAN-IVTLHDLIH----------TD
P24941      ALKKIRLDTE---TEGVPSTAIREISLLKEL---NHPN-IVKLLDVIH----------TE
O94921      ALKVIRLQE----EEGTPFTAIREASLLKGL---KHAN-IVLLHDIIH----------TK
Q00537      ALKEIRLEH----EEGAPCTAIREVSLLKDL---KHAN-IVTLHDIVH----------TD
            *:* :          *    : **   :       . . :: :                 

P21127      DKIYIVMNYVEHDLKSLMETMK--------QPFLPGEVKTLMIQLLRGVKHLHDNWILHR
Q9BWU1      RKVWLLFDYAEHDLWHIIKFHRASKANKKPMQLPRSMVKSLLYQILDGIHYLHANWVLHR
Q96Q40      ETLTFVFEYMHTDLAQYMSQHP--------GGLHPHNVRLFMFQLLRGLAYIHHQHVLHR
Q00526      RKLYLVFEFLSQDLKKYMDSTP-------GSELPLHLIKSYLFQLLQGVSFCHSHRVIHR
Q9NYV4      GAFYLVFEYMDHDLMGLLESGL--------VHFSEDHIKSFMKQLMEGLEYCHKKNFLHR
P50750      GSIYLVFDFCEHDLAGLLSNVL--------VKFTLSEIKRVMQMLLNGLYYIHRNKILHR
P50613      SNISLVFDFMETDLEVIIKDNS--------LVLTPSHIKAYMLMTLQGLEYLHQHWILHR
Q00534      TKLTLVFEHVDQDLTTYLDKVP-------EPGVPTETIKDMMFQLLRGLDFLHSHRVVHR
Q00536      KSLTLVFEYLDKDLKQYLDDCG--------NIINMHNVKLFLFQLLRGLAYCHRQKVLHR
P49336      RKVWLLFDYAEHDLWHIIKFHRASKANKKPVQLPRGMVKSLLYQILDGIHYLHANWVLHR
Q15131      ESIFLVMGYCEQDLASLLENMP--------TPFSEAQVKCIVLQVLRGLQYLHRNFIIHR
Q00535      KKLTLVFEFCDQDLKKYFDSCN--------GDLDPEIVKSFLFQLLKGLGFCHSRNVLHR
Q9UQ88      DKIYIVMNYVEHDLKSLMETMK--------QPFLPGEVKTLMIQLLRGVKHLHDNWILHR
P11802      IKVTLVFEHVDQDLRTYLDKAP-------PPGLPAETIKDLMRQFLRGLDFLHANCIVHR
P06493      SRLYLIFEFLSMDLKKYLDSIP------PGQYMDSSLVKSYLYQILQGIVFCHSRRVLHR
Q8IZL9      GGFVLAFEFMLSDLAEVVRHAQ--------RPLAQAQVKSYLQMLLKGVAFCHANNIVHR
Q14004      GAFYLVFEYMDHDLMGLLESGL--------VHFNENHIKSFMRQLMEGLDYCHKKNFLHR
Q07002      RSLTLVFEYLDSDLKQYLDHCG--------NLMSMHNVKIFMFQLLRGLAYCHHRKILHR
P24941      NKLYLVFEFLHQDLKKFMDASA-------LTGIPLPLIKSYLFQLLQGLAFCHSHRVLHR
O94921      ETLTLVFEYVHTDLCQYMDKHP--------GGLHPDNVKLFLFQLLRGLSYIHQRYILHR
Q00537      KSLTLVFEYLDKDLKQYMDDCG--------NIMSMHNVKLFLYQILRGLAYCHRRKVLHR
              . : : .   **   .              .    ::  :   : *: . * . .:**

P21127      DLKTSNLLLS----HAGILKVGDFGLAREYGS-P---LKAYTPVVVTLWYRAPELLLGAK
Q9BWU1      DLKPANILVMGEGPERGRVKIADMGFARLFNS-PLKPLADLDPVVVTFWYRAPELLLGAR
Q96Q40      DLKPQNLLIS----HLGELKLADFGLARAKSI-P---SQTYSSEVVTLWYRPPDALLGAT
Q00526      DLKPQNLLIN----ELGAIKLADFGLARAFGV-P---LRTYTHEVVTLWYRAPEILLGSK
Q9NYV4      DIKCSNILLN----NSGQIKLADFGLARLYNSEE---SRPYTNKVITLWYRPPELLLGEE
P50750      DMKAANVLIT----RDGVLKLADFGLARAFSLAKNSQPNRYTNRVVTLWYRPPELLLGER
P50613      DLKPNNLLLD----ENGVLKLADFGLAKSFGS-P---NRAYTHQVVTRWYRAPELLFGAR
Q00534      DLKPQNILVT----SSGQIKLADFGLARIYSF-----QMALTSVVVTLWYRAPEVLLQS-
Q00536      DLKPQNLLIN----ERGELKLADFGLARAKSI-P---TKTYSNEVVTLWYRPPDILLGST
P49336      DLKPANILVMGEGPERGRVKIADMGFARLFNS-PLKPLADLDPVVVTFWYRAPELLLGAR
Q15131      DLKVSNLLMT----DKGCVKTADFGLARAYGV-P---VKPMTPKVVTLWYRAPELLLGTT
Q00535      DLKPQNLLIN----RNGELKLADFGLARAFGI-P---VRCYSAEVVTLWYRPPDVLFGAK
Q9UQ88      DLKTSNLLLS----HAGILKVGDFGLAREYGS-P---LKAYTPVVVTQWYRAPELLLGAK
P11802      DLKPENILVT----SGGTVKLADFGLARIYSY-----QMALTPVVVTLWYRAPEVLLQS-
P06493      DLKPQNLLID----DKGTIKLADFGLARAFGI-P---IRVYTHEVVTLWYRSPEVLLGSA
Q8IZL9      DLKPANLLIS----ASGQLKIADFGLARVFSPDG---SRLYTHQVATRWYRAPELLYGAR
Q14004      DIKCSNILLN----NRGQIKLADFGLARLYSSEE---SRPYTNKVITLWYRPPELLLGEE
Q07002      DLKPQNLLIN----ERGELKLADFGLARAKSV-P---TKTYSNEVVTLWYRPPDVLLGST
P24941      DLKPQNLLIN----TEGAIKLADFGLARAFGV-P---VRTYTHEVVTLWYRAPEILLGCK
O94921      DLKPQNLLIS----DTGELKLADFGLARAKSV-P---SHTYSNEVVTLWYRPPDVLLGST
Q00537      DLKPQNLLIN----EKGELKLADFGLARAKSV-P---TKTYSNEVVTLWYRPPDVLLGSS
            *:*  *:*:       * :* .*:*:*:  .             * * *** *: *    

P21127      EYSTAVDMWSVGCIFGELLT-QKPLFPGKS---------EIDQINKVFKDLGTPSEKIWP
Q9BWU1      HYTKAIDIWAIGCIFAELLT-SEPIFHCRQEDIKTSNPFHHDQLDRIFSVMGFPADKDWE
Q96Q40      EYSSELDIWGAGCIFIEMFQ-GQPLFPGVSN--------ILEQLEKIWEVLGVPTEDTWP
Q00526      FYTTAVDIWSIGCIFAEMVT-RKALFPGDS---------EIDQLFRIFRMLGTPSEDTWP
Q9NYV4      RYTPAIDVWSCGCILGELFT-KKPIFQANL---------ELAQLELISRLCGSPCPAVWP
P50750      DYGPPIDLWGAGCIMAEMWT-RSPIMQGNT---------EQHQLALISQLCGSITPEVWP
P50613      MYGVGVDMWAVGCILAELLL-RVPFLPGDS---------DLDQLTRIFETLGTPTEEQWP
Q00534      SYATPVDLWSVGCIFAEMFR-RKPLFRGSS---------DVDQLGKILDVIGLPGEEDWP
Q00536      DYSTQIDMWGVGCIFYEMAT-GRPLFPGST---------VEEQLHFIFRILGTPTEETWP
P49336      HYTKAIDIWAIGCIFAELLT-SEPIFHCRQEDIKTSNPYHHDQLDRIFNVMGFPADKDWE
Q15131      TQTTSIDMWAVGCILAELLA-HRPLLPGTS---------EIHQIDLIVQLLGTPSENIWP
Q00535      LYSTSIDMWSAGCIFAELANAGRPLFPGND---------VDDQLKRIFRLLGTPTEEQWP
Q9UQ88      EYSTAVDMWSVGCIFGELLT-QKPLFPGNS---------EIDQINKVFKELGTPSEKIWP
P11802      TYATPVDMWSVGCIFAEMFR-RKPLFCGNS---------EADQLGKIFDLIGLPPEDDWP
P06493      RYSTPVDIWSIGTIFAELAT-KKPLFHGDS---------EIDQLFRIFRALGTPNNEVWP
Q8IZL9      QYDQGVDLWSVGCIMGELLN-GSPLFPGKN---------DIEQLCYVLRILGTPNPQVWP
Q14004      RYTPAIDVWSCGCILGELFT-KKPIFQANQ---------ELAQLELISRICGSPCPAVWP
Q07002      EYSTPIDMWGVGCIHYEMAT-GRPLFPGST---------VKEELHLIFRLLGTPTEETWP
P24941      YYSTAVDIWSLGCIFAEMVT-RRALFPGDS---------EIDQLFRIFRTLGTPDEVVWP
O94921      EYSTCLDMWGVGCIFVEMIQ-GVAAFPGMKD--------IQDQLERIFLVLGTPNEDTWP
Q00537      EYSTQIDMWGVGCIFFEMAS-GRPLFPGST---------VEDELHLIFRLLGTPSQETWP
                 :*:*. * *  *:       :                ::  :    *      * 

P21127      GYSELPAVKKMTFSE----HPYNNLRKRF--GALL-SDQGFDLMNKFLTYFPGRRISAED
Q9BWU1      DIRKMPEYPTLQKDFRRTTYANSSLIKYMEKHKVKPDSKVFLLLQKLLTMDPTKRITSEQ
Q96Q40      GVSKLPNYNPEWFPL----PTPRSLHVVW--NRLGRVPEAEDLASQMLKGFPRDRVSAQE
Q00526      GVTQLPDYKGS-FPK----WTRKGLEEIV--PNLE--PEGRDLLMQLLQYDPSQRITAKT
Q9NYV4      DVIKLPYFNTMKPKK----QYRRRLREEF--SFIP--SAALDLLDHMLTLDPSKRCTAEQ
P50750      NVDNYELYEKLELVK----GQKRKVKDRL--KAYVRDPYALDLIDKLLVLDPAQRIDSDD
P50613      DMCSLPDYVTF--KS----FPGIPLHHIF--SAAG--DDLLDLIQGLFLFNPCARITATQ
Q00534      RDVALPRQ---AFHS----KSAQPIEKFV--TDID--ELGKDLLLKCLTFNPAKRISAYS
Q00536      GILSNEEFKTYNYPK----YRAEALLSHA--PRLD--SDGADLLTKLLQFEGRNRISAED
P49336      DIKKMPEHSTLMKDFRRNTYTNCSLIKYMEKHKVKPDSKAFHLLQKLLTMDPIKRITSEQ
Q15131      GFSKLPLVGQYSLRK----QPYNNLKHKF--P-WL-SEAGLRLLHFLFMYDPKKRATAGD
Q00535      SMTKLPDYKPY-PMY----PATTSLVNVV--PKLN--ATGRDLLQNLLKCNPVQRISAEE
Q9UQ88      GYSELPVVKKMTFSE----HPYNNLRKRF--GALL-SDQGFDLMNKFLTYFPGRRISAED
P11802      RDVSLPRG---AFPP----RGPRPVQSVV--PEME--ESGAQLLLEMLTFNPHKRISAFR
P06493      EVESLQDYKNT-FPK----WKPGSLASHV--KNLD--ENGLDLLSKMLIYDPAKRISGKM
Q8IZL9      ELTELPDYNKISFKE----QVPMPLEEVL--PDVS--PQALDLLGQFLLYPPHQRIAASK
Q14004      DVIKLPYFNTMKPKK----QYRRKLREEF--VFIP--AAALDLFDYMLALDPSKRCTAEQ
Q07002      GVTAFSEFRTYSFPC----YLPQPLINHA--PRLD--TDGIHLLSSLLLYESKSRMSAEA
P24941      GVTSMPDYKPS-FPK----WARQDFSKVV--PPLD--EDGRSLLSQMLHYDPNKRISAKA
O94921      GVHSLPHFKPERFTL----YSSKNLRQAW--NKLSYVNHAEDLASKLLQCSPKNRLSAQA
Q00537      GISSNEEFKNYNFPK----YKPQPLINHA--PRLD--SEGIELITKFLQYESKKRVSAEE
                                    .                 *    :      *  .  

P21127      GLKHEYFRETPLPIDPSMFPT---------WPAKSEQQ-------------RVKRGTSP-
Q9BWU1      ALQDPYFQEDPLPTLDVFA------GCQIPYPKREFLNEDDPEEKGDKNQQQQQNQHQQP
Q96Q40      ALVHDYFSALPSQLYQLPDEE-------SLFTVSGVRL-------------KPEMCDL--
Q00526      ALAHPYFSSPE-PSPAARQYV-----------LQRFRH----------------------
Q9NYV4      TLQSDFLKDVELSKMAPPDLP-HWQDCHELWS-KKRRR-------------QRQSGVVVE
P50750      ALNHDFFWSDPMPSDLKGMLSTHL---TSMFEYLAPPR-------------RKGSQIT--
P50613      ALKMKYFSNRPGPTPGCQLPR-------PNCPVETLKE-------------QSNPALA--
Q00534      ALSHPYFQDLERCKENLDSHLPPSQNTSELNTA---------------------------
Q00536      AMKHPFFLSLGERIHKLPDTT-------SIFALKEIQL-------------QKEASLR--
P49336      AMQDPYFLEDPLPTSDVFA------GCQIPYPKREFLTEEEPDDKGDKKNQQQQQGNNH-
Q15131      CLESSYFKEKPLPCEPELMPT---------FPHHRNKR-------------AAPA-----
Q00535      ALQHPYFSDFCPP-----------------------------------------------
Q9UQ88      GLKHEYFRETPLPIDPSMFPT---------WPAKSEQQ-------------RVKRGTSP-
P11802      ALQHSYLHKDEGNPE---------------------------------------------
P06493      ALNHPYFNDLDNQIKKM-------------------------------------------
Q8IZL9      ALLHQYFFTAPLPAHPSELPI-------PQRL-GGPAP-------------KAHPGPPHI
Q14004      ALQCEFLRDVEPSKMPPPDLP-LWQDCHELWS-KKRRR-------------QKQMGMTDD
Q07002      ALSHSYFRSLGERVHQLEDTA-------SIFSLKEIQL-------------QKDPGYR--
P24941      ALAHPFFQDVTKPVPHLRL-----------------------------------------
O94921      ALSHEYFSDLPPRLWELTDMS-------SIFTVPNVRL-------------QPEAGES--
Q00537      AMKHVYFRSLGPRIHALPESV-------SIFSLKEIQL-------------QKDPGFR--
             :   ::                                                     

P21127      -RPPE------GG-----------LGYSQLGDDDLKETGFHLTTTNQGASAAGPGFSLK-
Q9BWU1      TAPPQQ----AAA-----------PPQAPPPQQNSTQTNGTAGGAGAGVGGTGAGLQHSQ
Q96Q40      ----------LAS-----------YQKGHHPAQFSKCW----------------------
Q00526      ------------------------------------------------------------
Q9NYV4      EPPPSKTSRKETTSGTSTEPVKNSSPAPPQPAPGKVESGAG-----DAIGLADITQQLNQ
P50750      Q----------QS-----------TNQSRNPAT------------------------TNQ
P50613      IK-----RKRTEA-----------LEQGGLPKKLIF------------------------
Q00534      ------------------------------------------------------------
Q00536      ----------SSS-----------MPDSGRPAFRVVDTEF--------------------
P49336      --------------------------------------------------TNGTGHPGNQ
Q15131      --TSE------GQ-----------SKRCKP------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      -RPPE------GG-----------LGYSQLGDDDLKETGFHLTTTNQGASAAGPGFSLK-
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      HD-----FHVDRP-----------LEESLLNPELIRPFIL-----------EG-------
Q14004      VST-IKAPRKDLSLGLDDS--RTNTPQGVLPSSQLKSQGSS----NVAPVKTGPGQHLNH
Q07002      ----------GLA-----------FQQPGRGKNRRQSIF---------------------
P24941      ------------------------------------------------------------
O94921      ----------MRA-----------FGKNNSYGKSLSNSKH--------------------
Q00537      ----------NSS-----------YPETGHGKNRRQSMLF--------------------
                                                                        

P21127      ------------F-----------------------------------------------
Q9BWU1      DSSLNQVPPNKKPRLGPSGANSGGP--------VMPSDYQHSSSRLNYQSSV--QGSSQS
Q96Q40      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      SELAV------LLNLLQSQTDLSIPQMAQLLNIHSNPEMQQQLEALNQSISALTEATSQQ
P50750      TEFER------VF-----------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
P49336      DSSHTQGPPLKKVRVVPPTTTSGGL--------IMTSDYQRSNPHAAYPNPG--PSTSQP
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      ------------F-----------------------------------------------
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      SELAI------LLNLLQSKTSVNMADFVQVLNIKVNSETQQQLNKINLPAGILATGEKQT
Q07002      ------------------------------------------------------------
P24941      ------------------------------------------------------------
O94921      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
                                                                        

P21127      ------------------------------------------------------------
Q9BWU1      QST----------LGYSSSSQQSSQYHPSHQAHRY-------------------------
Q96Q40      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      QDSETMAPEES--L-KEAPSA--PVILPSAEQTTLEASSTPADMQNILAVLLSQLMKTQE
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
P49336      QSS----------MGYSATSQQPPQYS--HQTHRY-------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      ------------------------------------------------------------
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      DPSTP-QQESSKPLGGIQPSS--QTIQP-----KVETDAAQAAVQSAFAVLLTQLIKAQQ
Q07002      ------------------------------------------------------------
P24941      ------------------------------------------------------------
O94921      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
                                                                        

P21127      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      PAGS---LEENNSDKNSGPQG-----PRRTPTM----------------PQEEAAACPPH
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      ------------------------------------------------------------
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      SKQKDVLLEERE--NGSGHEASLQLRPPPEPSTPVSGQDDLIQHQDMRILELTPEPDRPR
Q07002      ------------------------------------------------------------
P24941      ------------------------------------------------------------
O94921      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
                                                                        

P21127      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      ILPPEKRPPEPPGPPPPPPPPPLVEGDLSSAP------------QELNPAVTAALLQLLS
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      ------------------------------------------------------------
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      ILPPDQRPPEPPEPPP------VTEEDLDYRTENQHVPTTSSSLTDPHAGVKAALLQLLA
Q07002      ------------------------------------------------------------
P24941      ------------------------------------------------------------
O94921      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
                                                                        

P21127      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      QPEAE--PPGHLPHEHQALRPMEYSTRPRPNRTYGNTDGPETGFSAIDTDERNSGPALTE
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      ------------------------------------------------------------
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      QHQPQDDPKREGGIDYQA--GDTYVSTSDYKDNFGSSSFSSAPYVSNDGLGSSSAPPLER
Q07002      ------------------------------------------------------------
P24941      ------------------------------------------------------------
O94921      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
                                                                        

P21127      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      ------SLVQTL-----------------VKNRTFSGSLSHLGESSSYQGTGSVQFPGDQ
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      ------------------------------------------------------------
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      RSFIGNSDIQSLDNYSTASSHSGGPPQPSAFSESFPSS--VAGYGDIYLNAGPMLFSGDK
Q07002      ------------------------------------------------------------
P24941      ------------------------------------------------------------
O94921      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
                                                                        

P21127      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
Q9NYV4      DLRFARVP--LALHPVVGQPFLKAEGSSNSVVHAETKLQNYGELGPGTTGASSSGAGLHW
P50750      ------------------------------------------------------------
P50613      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
P49336      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q9UQ88      ------------------------------------------------------------
P11802      ------------------------------------------------------------
P06493      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
Q14004      DHRFEYSHGPIAVLANSSDPSTGPE--STHPLPAKMHNYNYGGNLQENPSGPSLMHGQTW
Q07002      ------------------------------------------------------------
P24941      ------------------------------------------------------------
O94921      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
                                                                        

P21127      -------------------------------
Q9BWU1      -------------------------------
Q96Q40      -------------------------------
Q00526      -------------------------------
Q9NYV4      GGPTQSSAYGKLYRGPTRVPPRGGRGRGVPY
P50750      -------------------------------
P50613      -------------------------------
Q00534      -------------------------------
Q00536      -------------------------------
P49336      -------------------------------
Q15131      -------------------------------
Q00535      -------------------------------
Q9UQ88      -------------------------------
P11802      -------------------------------
P06493      -------------------------------
Q8IZL9      -------------------------------
Q14004      TSPAQGPGYSQGYRGHISTSTGRGRGRGLPY
Q07002      -------------------------------
P24941      -------------------------------
O94921      -------------------------------
Q00537      -------------------------------
                                           
