CLUSTAL O(1.2.3) multiple sequence alignment


P24941      ---------MENFQKVEKIGEGTYGVVYKARNKL-TGEVVALKKIRLDTE---TEGVPST
P11802      -------MATSRYEPVAEIGVGAYGTVYKARDPH-SGHFVALKSVRVPNGGGGGGGLPIS
Q00534      MEKDGLCRADQQYECVAEIGEGAYGKVFKARDLKNGGRFVALKRVRVQTG---EEGMPLS
                      ..:: * :** *:** *:***:    *..**** :*: .      *:* :

P24941      AIREISLLK---ELNHPNIVKLLDVIH-----TENKLYLVFEFLHQDLKKFMDASALTGI
P11802      TVREVALLRRLEAFEHPNVVRLMDVCATSRTDREIKVTLVFEHVDQDLRTYLDKAPPPGL
Q00534      TIREVAVLRHLETFEHPNVVRLFDVCTVSRTDRETKLTLVFEHVDQDLTTYLDKVPEPGV
            ::**:::*:    ::***:*:*:**        * *: ****.:.*** .::*     *:

P24941      PLPLIKSYLFQLLQGLAFCHSHRVLHRDLKPQNLLINTEGAIKLADFGLARAFGVPVRTY
P11802      PAETIKDLMRQFLRGLDFLHANCIVHRDLKPENILVTSGGTVKLADFGLARIYSYQMA-L
Q00534      PTETIKDMMFQLLRGLDFLHSHRVVHRDLKPQNILVTSSGQIKLADFGLARIYSFQMA-L
            *   **. : *:*:** * *:: ::******:*:*:.: * :********* :.  :   

P24941      THEVVTLWYRAPEILLGCKYYSTAVDIWSLGCIFAEMVTRRALFPGDSEIDQLFRIFRTL
P11802      TPVVVTLWYRAPEVLLQST-YATPVDMWSVGCIFAEMFRRKPLFCGNSEADQLGKIFDLI
Q00534      TSVVVTLWYRAPEVLLQSS-YATPVDLWSVGCIFAEMFRRKPLFRGSSDVDQLGKILDVI
            *  **********:** .. *:* **:**:*******. *: ** *.*: *** :*:  :

P24941      GTPDEVVWPGVTSMPDYKPSFPKWARQDFSKVVPPLDEDGRSLLSQMLHYDPNKRISAKA
P11802      GLPPEDDWPRDVSLPR--GAFPPRGPRPVQSVVPEMEESGAQLLLEMLTFNPHKRISAFR
Q00534      GLPGEEDWPRDVALPR--QAFHSKSAQPIEKFVTDIDELGKDLLLKCLTFNPAKRISAYS
            * * *  **  .::*    :*   . : ....*  ::* * .** : * ::* *****  

P24941      ALAHPFFQDVTKPVPHLRL--------------
P11802      ALQHSYLHKDEGNPE------------------
Q00534      ALSHPYFQDLERCKENLDSHLPPSQNTSELNTA
            ** * :::.                        
